"""Update repository schema

Revision ID: d761a9b14de5
Revises: initial_migration
Create Date: 2025-01-30 13:30:04.123015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd761a9b14de5'
down_revision: Union[str, None] = 'initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('best_practices', sa.Column('category', sa.String(), nullable=False))
    op.add_column('best_practices', sa.Column('is_generalizable', sa.Boolean(), nullable=True))
    op.add_column('best_practices', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.alter_column('best_practices', 'repository_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('best_practices', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('best_practices', 'code_snippet',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(None, 'best_practices', type_='foreignkey')
    op.create_foreign_key(None, 'best_practices', 'repositories', ['repository_id'], ['id'])
    op.drop_column('best_practices', 'line_numbers')
    op.drop_column('best_practices', 'metadata')
    op.drop_column('best_practices', 'updated_at')
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('files', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'repositories', ['repository_id'], ['id'])
    op.add_column('repositories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('last_analyzed', sa.DateTime(), nullable=True))
    op.add_column('repositories', sa.Column('analysis_status', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('analysis_progress', sa.Float(), nullable=True))
    op.add_column('repositories', sa.Column('cached_until', sa.DateTime(), nullable=True))
    op.alter_column('repositories', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('repositories', 'analysis_cache')
    op.drop_column('repositories', 'last_analyzed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_analyzed_at', sa.DATETIME(), nullable=True))
    op.add_column('repositories', sa.Column('analysis_cache', sqlite.JSON(), nullable=True))
    op.alter_column('repositories', 'is_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('repositories', 'cached_until')
    op.drop_column('repositories', 'analysis_progress')
    op.drop_column('repositories', 'analysis_status')
    op.drop_column('repositories', 'last_analyzed')
    op.drop_column('repositories', 'description')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.alter_column('files', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('chat_messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('best_practices', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.add_column('best_practices', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.add_column('best_practices', sa.Column('line_numbers', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'best_practices', type_='foreignkey')
    op.create_foreign_key(None, 'best_practices', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.alter_column('best_practices', 'code_snippet',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('best_practices', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('best_practices', 'repository_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('best_practices', 'extra_data')
    op.drop_column('best_practices', 'is_generalizable')
    op.drop_column('best_practices', 'category')
    # ### end Alembic commands ###
